### ISSUE TITLE
Chrome "this browser is managed by your organization"

### ISSUE THREAD

**Issue by cobra-7777** [builtbybel/Winpilot#39]
Will BloatNosy cause this message in chrome if you disable chrome telemetry?

I have a complete fresh install of windows 11, so i find it hard to believe that i already have malware. (Google results say its malware if you see this message on a personal computer).

**Comment by bxbi-exe** [comment]
It happened to me too

**Comment by Vipin2003** [comment]
Yup..it happens. It was perfect in ThisisWin11 (outdated) as there is no such warning.

**Comment by MiguelMachado-dev** [comment]
> The reason Chrome is telling you that is because the app is setting registry values that Chrome uses to disable metrics & other telemetry items.

https://github.com/builtbybel/BloatyNosy/issues/6#issuecomment-1447444636

**Comment by mkstevens** [comment]
deal breaker

**Comment by sidsharths1245** [comment]
Happened to me too, I freaked out and reset my PC and all the passwords thinking I had gotten a malware. After the fresh install when I ran this app again, this time the warning appeared in the systems privacy settings. Is there a way to disable this? It seems the app applies some kind of group policy or sopmething.
![image](https://github.com/builtbybel/BloatyNosy/assets/64619769/1501cf90-6f70-4755-92a3-ff5f9afa59d1)

**Comment by esoterial** [comment]
If you want to disable this, because it can restrict your Google Sign In with certain 3rd party applications, simply go into your Registry Editor, type in this path:
```
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome
```
and delete these 3 values;

![image](https://github.com/builtbybel/BloatyNosy/assets/31023006/4d2e6d54-817b-4e79-bef0-5174c2d72350)

[This way](https://support.google.com/chrome/a/answer/9131254?hl=en#zippy=%2Cexample-settings%2Cconfigure-settings-on-windows-computers) is probably how it was done by BloatyNosy. Maybe the same can be applied with the Windows diagnostics prevention if you find the right documentation but I don't see any problem with it, if anything, it prevents Windows updates from enabling it again.

**Comment by himynameisubik** [comment]
Was looking for why this happened to me as I was using BlaotyNosy but also used Optimizer (https://github.com/hellzerg/optimizer) at some point. So for me it was all these entries that caused the "Managed by your organization" message. 

![image](https://github.com/builtbybel/BloatyNosy/assets/322449/6408810f-60b0-480a-aa39-0f703aa30820)
