### ISSUE TITLE
thanks for removing HP bloatware/spyware, but it keeps coming back

### ISSUE THREAD

**Issue by papyr** [builtbybel/Winpilot#5]
Hello I wanted to thank you sincerely for removing the H.P bloatware and spyware.

Can you recommend a way to keep it off,

**Comment by tpkowastaken** [comment]
which apps are coming back exactly? It could be just not fully removed with an autoupdater just "updating the app" which just installs it back. Try taking a look at those apps with [revo uninstaller](https://www.revouninstaller.com/revo-uninstaller-free-download/). Otherwise you might look into some registry hacks on internet that could just restrict updating it in some way or another. You could also disable anything bloatware related in [autoruns](https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns) that might be installing it back. Hope it helps!
